-- Get polygons in the given bounding box 
-- Along with the colour index so know what colour to draw it 
--Clip the polygons  to limit data points returned to application 
-- Include bounding box for relation so know if can draw the label 
SELECT
    AsText(
        ST_INTERSECTION (
            BuildMBR ( :west, :south, :east, :north, 4326 ),
            p.polygonX
        )
    ),   --AsText 
    -- Use MAX() to select a single value for each element. 
    -- COALESCE then picks the English name (if present), falling back to the generic 'name' tag.
    COALESCE(MAX(t_name_en.value), MAX(t_name.value)),
    r.colourIndex,
    r.minX, r.minY, r.maxX, r.maxY,
    r.labelX, r.labelY
  FROM 
    spt_polygons AS p
    INNER JOIN tbl_polygonOwners AS po ON po.polygonId = p.polygonId AND po.elementType = 3
    INNER JOIN tbl_layerPolygons AS lp ON lp.polygonId = p.polygonId
    INNER JOIN tbl_countries AS r ON r.RelationID = po.elementID AND po.elementType = 3

    -- Use LEFT JOIN for tags:
    -- This prevents row duplication from the tag table generating one row for every tag.
    -- It also ensures the polygon is returned even if the specific tag is missing (e.g., no 'name:en').
    LEFT JOIN tbl_Tags AS t_name ON po.elementID = t_name.elementID AND t_name.key = 'name'
    LEFT JOIN tbl_Tags AS t_name_en ON po.elementID = t_name_en.elementID AND t_name_en.key = 'name:en'

  WHERE
    ( lp.layerId = 1 OR lp.layerId = 4 )
    AND p.polygonX IS NOT NULL
    AND :zoomBand  <= 100 -- p.displayLessThan

    -- Use the spatial index for initial filter based on the bounding box
    AND p.ROWID IN (
        SELECT ROWID
        FROM SpatialIndex
        WHERE
            f_table_name = 'spt_polygons'
            AND f_geometry_column = 'polygon1'
            AND search_frame = BuildMBR ( :west, :south, :east, :north, 4326 )
    )
    AND ( GeometryType( p.polygonX ) = 'POLYGON' OR GeometryType( p.polygonX ) = 'MULTIPOLYGON' )

  -- GROUP BY ensures that all the rows potentially generated by the LEFT JOINs 
  -- (one row for 'name', one row for 'name:en', one row for 'name:de', etc.) 
  -- are collapsed into a single result row per unique polygon/element.
  GROUP BY
    p.polygonId, -- Grouping by polygonId is the most specific identifier
    r.minX, r.minY, r.maxX, r.maxY;